import Head from 'next/head'
import Footer from "../component/footer"
import Header from "../component/header"
import Gallery from "../component/gallery"


export default function Contactus({data}) {

  const galleryMeta = data.find( (item) =>  item.Page == 'Contact' ? item : null )

    return (
      // <div className={styles.container}>
      <div className='home-page'>
        <Head>
          <title>Gallery Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/fev.ico" />
        </Head>


        <Header/>
            <Gallery/>
        <Footer />


        
      </div>
    )
  }




  
  